name: Run All Tests
on:
  push:
    branches:
     - '**'
  pull_request:
    branches:
     - '**'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright Musigrow App
        run: cd apps/musigrow-app && npx playwright install --with-deps
      - name: Run Jest Musigrow App
        run: cd apps/musigrow-app && yarn test
      - name: Run Playwright Tests Musigrow App
        run: cd apps/musigrow-app && yarn test:e2e
      - name: Install Playwright Musigrow UI
        run: cd packages/musigrow-ui &&npx playwright install --with-deps
      - name: Run Jest Musigrow UI
        run: cd packages/musigrow-ui && yarn test
      - name: Run Playwright Tests Musigrow UI
        run: cd packages/musigrow-ui && yarn test:e2e
